GET http://localhost:8085/users
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImpheXBhdGVsQGdtYWlsLmNvbSIsIkZpcnN0X25hbWUiOiJKYXkiLCJMYXN0X25hbWUiOiJQYXRlbCIsIlVpZCI6IjY1ZDBlZDViZTUzZGEyNDI3MTJkNmY2NyIsIlVzZXJfdHlwZSI6IkFETUlOIiwiZXhwIjoxNzA4Mjc3NTE2fQ.Bfy7MFH0I6fcEv1QmAbC4Kki56ZDyShoUWhhVZDCkG0